//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEngineeringSystemApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDashboardOption
    {
        public int UserDashboardOptionsID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserDashboardOption1 { get; set; }
    
        public virtual DashboardOption DashboardOption { get; set; }
        public virtual User User { get; set; }
    }
}
